repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.2
    hooks:
      - id: uv-lock
