[tool.poetry]
name = "pcomp"
version = "0.1.0"
description = ""
authors = ["Cameron Pitsch <cameron.pitsch@rwth-aachen.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pm4py = "^2.7.8.2"
pandas = "^2.1.2"
scikit-learn = "^1.3.2"
wasserstein = "1.0.1"
tqdm = "^4.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
