[tool.poetry]
name = "pcomp"
version = "0.1.0"
description = ""
authors = ["Cameron Pitsch <cameron.pitsch@rwth-aachen.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pm4py = "^2.7.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
