# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# Built using template: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and Check Formatting of Python Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: abatilo/actions-poetry@v2.3.0
    - name: Install dependencies
      run: |
        poetry check
        poetry install
    - uses: psf/black@stable
      with:
        version: "23.11.0" # Same version as in poetry.toml file
    - name: Test with pytest
      run: |
        poetry run pytest
